name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyver }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install 'Cython' 'tox<4'

    - name: Run unittest
      run: |
        version=${{ matrix.pyver }}
        tox -e py${version/./}
